---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
        - name: api-user
          image: registry.cloud.okteto.net/thejatmik/api_user:latest
          ports:
            - containerPort: 6968
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: text-api
  template:
    metadata:
      labels:
        app: text-api
    spec:
      - name: api-text
        image: registry.cloud.okteto.net/thejatmik/api_text:latest
        ports:
          - containerPort: 6969
