apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-text
spec:
  selector:
    matchLabels:
      app: api_text
  replicas: 1
  template:
    metadata:
      labels:
        app: api_text
    spec:
      containers:
      - name: api-text
        image: registry.cloud.okteto.net/thejatmik/api_text:latest
        ports:
          - containerPort: 6969
