apiVersion: v1beta1
kind: Deployment
metadata:
  name: yes-site
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: api-user
          image: registry.cloud.okteto.net/thejatmik/api_user:latest
          ports:
            - containerPort: 6969
        - name: api-text
          image: registry.cloud.okteto.net/thejatmik/api_text:latest
          ports:
            - containerPort: 6969
