---
apiVersion: v1
kind: Service
metadata:
  name: mongodb01
  labels:
    app: mongodb01
spec:
  clusterIP: None
  selector:
    app: mongodb01
---
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: mongodb01
  spec:
    serviceName: mongodb01
    replicas: 1
    selector:
      matchLabels:
        app: mongodb01
    template:
      metadata:
        labels:
          app: mongodb01
      spec:
        containers:
        - name: mongodb-standalone
          image: docker.io/mongo:bionic
          env:
            - name: MONGO_INITDB_ROOT_USERNAME_FILE
              value: /etc/mongodb/admin/MONGO_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD_FILE
              value: /etc/mongodb/admin/MONGO_ROOT_PASSWORD
          volumeMounts:
          - name: mongodb
            mountPath: /etc/mongodb
            readOnly: true
        volumes:
        - name: mongodb
          secret:
            secretName: mongodb
            items:
            - key: MONGO_ROOT_USERNAME
              path: admin/MONGO_ROOT_USERNAME
              mode: 0444
            - key: MONGO_ROOT_PASSWORD
              path: admin/MONGO_ROOT_PASSWORD
              mode: 0444
