---
apiVersion: v1
kind: Service
metadata:
  name: mongodb01
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb01
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb01
spec:
  serviceName: mongodb01
  replicas: 1
  selector:
    matchLabels:
      app: mongodb01
  template:
    metadata:
      labels:
        app: mongodb01
    spec:
      securityContext:
        fsGroup: 1001
      initContainers:
      containers:
      - name: mongodb
        image: docker.io/bitnami/mongodb:4.0.12-debian-9-r43
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
        env:
        - name: MONGODB_PASSWORD
          value: "password"
        - name: MONGODB_ROOT_PASSWORD
          value: "password"
        - name: MONGODB_USERNAME
          value: "okteto"
        - name: MONGODB_SYSTEM_LOG_VERBOSITY
          value: "0"
        - name: MONGODB_DISABLE_SYSTEM_LOG
          value: "no"
        - name: MONGODB_DATABASE
          value: "okteto"
        - name: MONGODB_ENABLE_IPV6
          value: "no"
        - name: MONGODB_ENABLE_DIRECTORY_PER_DB
          value: "no"
        ports:
        - name: mongodb
          containerPort: 27017
        volumeMounts:
        - name: data
          mountPath: /bitnami/mongodb
          subPath:
        resources:
          {}
      volumes:
      - name: data
        emptyDir: {}
