---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb
type: Opaque
data:
  mongodb-root-pass: password
  mongodb-password: passowrd
---
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: mongodb
  spec:
    serviceName: mongodb
    replicas: 1
    selector:
      matchLabels:
        app: web
    template:
      metadata:
        labels:
          app: web
      spec:
        securityContext:
          fsGroup: 1001
        initContainers:
        containers:
        - name: mongodb
          image: docker.io/bitnami/mongodb:4.0.12-debian-9-r43
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          env:
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: mongodb-pass
          - name: MONGODB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: mongodb-root-password
          - name: MONGODB_USERNAME
            value: "okteto"
          - name: MONGODB_SYSTEM_LOG_VERBOSITY
            value: "0"
          - name: MONGODB_DISABLE_SYSTEM_LOG
            value: "no"
          - name: MONGODB_DATABASE
            value: "okteto"
          - name: MONGODB_ENABLE_IPV6
            value: "no"
          - name: MONGODB_ENABLE_DIRECTORY_PER_DB
            value: "no"
          ports:
          - name: mongodb
            containerPort: 27017
          volumeMounts:
          - name: data
            mountPath: /bitnami/mongodb
            subPath:
          resources:
            {}
        volumes:
        - name: data
          emptyDir: {}
