---
apiVersion: v1
kind: Service
metadata:
  name: postgres01
spec:
  ports:
  - port: 5432
  selector:
    app: postgres01
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres01
  replicas: 1
  selector:
    matchLabels:
      app: postgres01
  template:
    metadata:
      labels:
        app: postgres01
    spec:
      containers:
      - name: postgres
        image: docker.io/postgres:12-alpine
        env:
        - name: POSTGRES_PASSWORD
          value: "postgres"
        ports:
        - name: postgres
          containerPort: 5432
