apiVersion: v1
kind: Service
metadata:
  name: api_text
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 6969
  selector:
    app: web
---
apiVersion: v1
kind: Service
metadata:
  name: api_user
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 6968
  selector:
    app: web
