apiVersion: v1
kind: Service
metadata:
  name: text-api
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 6969
  selector:
    app: text-api
---
apiVersion: v1
kind: Service
metadata:
  name: user-api
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 6968
  selector:
    app: user-api
