---
apiVersion: v1
kind: Service
metadata:
  name: text-api
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 6969
  selector:
    app: text-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: text-api
  template:
    metadata:
      labels:
        app: text-api
    spec:
      containers:
      - name: api-text
        image: registry.cloud.okteto.net/thejatmik/api_text:latest
        ports:
        - containerPort: 6969
        env:
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: mongodb-password
        - name: MONGODB_USERNAME
          value: "okteto"
        - name: MONGODB_DATABASE
          value: "okteto"
        - name: POSTGRES_PASSWORD
          value: "postgres"
