---
apiVersion: v1
kind: Service
metadata:
  name: user-api
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 6968
  selector:
    app: user-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
      - name: api-user
        image: registry.cloud.okteto.net/thejatmik/api_user:latest
        ports:
        - containerPort: 6968
        env:
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mongodb-password
        - name: MONGODB_USERNAME
          value: "okteto"
        - name: MONGODB_DATABASE
          value: "okteto"
        - name: MONGODB_HOST
          value: mongodb01
        - name: MONGODB_PORT
          value: "27017"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_HOST
          value: postgres01
