---
apiVersion: v1
kind: Service
metadata:
  name: user-api
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 6968
  selector:
    app: user-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
      - name: api-user
        image: registry.cloud.okteto.net/thejatmik/api_user:latest
        ports:
        - containerPort: 6968
