name: Scheduler-Okteto

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  schedule_destroy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: "Login Okteto"
      uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: "Activate Namespace"
      uses: okteto/namespace@master
      with:
        name: thejatmik

    - name: "Destroy pipeline"
      uses: okteto/destroy-pipeline@master
  
  schedule_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: Login
      uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: "Activate Namespace"
      uses: okteto/namespace@master
      with:
        name: thejatmik

    - name: "Trigger the pipeline"
      uses: okteto/pipeline@master
