name: Build and Push to dockerhub

on:
  push:
    branches:
      - master

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
    - name: Login to dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push user-api
      uses: docker/build-push-action@v2
      with:
        context: ./api_user
        file: ./api_user/Dockerfile
        push: true
        tags: thejatmik/okt-user-api:latest
